builds:
  - binary: sema
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
      - GO111MODULES=on

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: sema
    homepage: https://github.com/sharpvik/sema
    tap:
      owner: sharpvik
      name: homebrew-sema
    commit_author:
      name: Viktor A. Rozenko Voitenko
      email: sharp.vik@gmail.com

checksum:
  name_template: "checksums.txt"
